### ISSUE TITLE
Where is the documentation for "rex" ?

### ISSUE THREAD

**Issue by mingodad** [GuntherRademacher/rex-parser-benchmark#1]
Hello Gunther !

It's impressive the number of targets that `rex` has but where is the documentation for it ?
Railroad diagram for it's grammar ?
And finally can/when it be opensource ?

Meanwhile I'm developing an `Yacc/Lex` compatible online editor/interpreter/tester here https://mingodad.github.io/parsertl-playground/playground/ repository here https://github.com/mingodad/parsertl-playground .

Would be nice to have something similar for `rex` ?

Cheers !

**Comment by GuntherRademacher** [comment]
REx is not open source at this time, and there is no published documentation available either. Sorry.
